version: '3'
services:
  database:
    image: 'mongo'
    restart: 'unless-stopped'
    container_name: 'repmap-mongodb-container'
    environment:
      - MONGO_INITDB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGODB_USER
      - MONGODB_PASS
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
